#pragma once

// BMS Master Configuration

#define BMS_BANK_COUNT 1
#define BMS_BANK_CELL_COUNT 7
#define BMS_BANK_TEMP_COUNT BMS_BANK_CELL_COUNT

#define BMS_FAULT_TEMP_THRESHOLD_HIGH 0xFFFF
#define BMS_FAULT_TEMP_THRESHOLD_LOW 0x0000

#define BMS_FAULT_VOLTAGE_THRESHOLD_HIGH 0xFFFF
#define BMS_FAULT_VOLTAGE_THRESHOLD_LOW 0x0000
